# Generated by Django 6.0.7 on 2026-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, verbose_name='اسم الباقة (عربي)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Plan Name (English)')),
                ('price', models.CharField(max_length=50, verbose_name='السعر')),
                ('features_ar', models.TextField(help_text='أدخل كل ميزة في سطر جديد (عربي)')),
                ('features_en', models.TextField(help_text='Enter each feature on a new line (English)')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='اسم المشروع (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Project Name (English)')),
                ('description_ar', models.TextField(verbose_name='وصف المشروع (عربي)')),
                ('description_en', models.TextField(verbose_name='Project Description (English)')),
                ('image', models.ImageField(upload_to='projects/')),
                ('category_ar', models.CharField(max_length=100, verbose_name='التصنيف (عربي)')),
                ('category_en', models.CharField(max_length=100, verbose_name='Category (English)')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان الخدمة (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Service Title (English)')),
                ('description_ar', models.TextField(verbose_name='وصف الخدمة (عربي)')),
                ('description_en', models.TextField(verbose_name='Service Description (English)')),
                ('icon_class', models.CharField(help_text='FontAwesome class e.g. fas fa-code', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(default='علي القفيلي للبرمجيات', max_length=100)),
                ('site_name_en', models.CharField(default='Ali Al-Qafili Software', max_length=100)),
                ('hero_title_ar', models.CharField(max_length=200)),
                ('hero_title_en', models.CharField(max_length=200)),
                ('hero_subtitle_ar', models.TextField()),
                ('hero_subtitle_en', models.TextField()),
                ('about_text_ar', models.TextField()),
                ('about_text_en', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address_ar', models.CharField(max_length=300)),
                ('address_en', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('position_ar', models.CharField(max_length=100, verbose_name='المنصب (عربي)')),
                ('position_en', models.CharField(max_length=100, verbose_name='Position (English)')),
                ('content_ar', models.TextField(verbose_name='الشهادة (عربي)')),
                ('content_en', models.TextField(verbose_name='Testimonial (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
